version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${NAMEDB}
      MYSQL_USER: ${USERDB}
      MYSQL_PASSWORD: ${PASSDB}
      DB_HOST: ${HOSTDB}
    ports:
      - "3306:3306"

  api:
    depends_on:
      - db
    container_name: api
    ports: 
      - "9000:9000"
    environment: 
      MYSQL_USER: ${USERDB}
      MYSQL_PASSWORD: ${PASSDB}
      MYSQL_DATABASE: ${NAMEDB}
    build: 
      context: ./
      dockerfile: build/Dockerfile-api

volumes:
  db-data: