version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: ${DB_HOST}
    ports:
      - "3306:3306"

  api:
    depends_on:
      - db
    container_name: api
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: ${DB_HOST}
    build:
      context: ./
      dockerfile: build/Dockerfile-api

volumes:
  db-data:
