name: Doc

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  doc:
    name: Make documentation
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: make documentation
        run: echo "Generate documentation"

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - shell: bash
        run: |
          cat linter.txt`
