name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.14.1"

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Create .artifacts folder
        run: |
          mkdir -p .artifacts
          ls -a

      - name: Lint
        if: ${{ failure() }}
        run: |
          ls
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          cd .artifacts
          golangci-lint run > linter.txt
          ls -a
          cd ..
          ls -a

      - name: Archive dev artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: .artifacts

      - name: Tests
        run: |
          go test ./... -v
